seed: 6174
# model
model:
  resnet_cifar:
    num_classes: 10
    num_layers: 20
# data
train_data:
  cifar10:
    train: true
val_data:
  cifar10:
    train: false
# training:
train_batch_size: 1024
val_batch_size: 1000
optimizer:
  sgd:
    lr: 1.6
    momentum: 0.9
    weight_decay: 0.0001
schedulers:
  multistep:
    milestones:
    - 3920ba
    - 5880ba
    gamma: 0.1
max_duration: 7840ba
algorithms:
  channels_last: {}
callbacks:
  lr_monitor: {}
# boilerplate
loggers:
  file:
    log_level: 3
  wandb:
    project: lth_diet
    entity: prunes
    tags: lr_data_warm_cf10_rn20
dataloader:
  persistent_workers: false
object_store:
  provider: google_storage
  container: prunes
  key_environ: GCS_KEY