seed: 6174
# model
model:
  resnet_cifar:
    num_classes: 10
    num_layers: 20
# data
train_data:
  cifar10:
    train: true
val_data:
  cifar10:
    train: false
# training:
train_batch_size: 1024
val_batch_size: 1000
optimizer:
  sgd:
    lr: 3.2
    momentum: 0.9
    weight_decay: 0.0001
schedulers:
  linear:
    alpha_i: 0.0
    alpha_f: 1.0
max_duration: 1600ba
algorithms:
  channels_last: {}
callbacks:
  lr_monitor: {}
# boilerplate
loggers:
  file:
    log_level: 3
  wandb:
    project: lth_diet
    entity: prunes
    tags: warmup_ablate_cf10_rn20
dataloader:
  persistent_workers: false
object_store:
  provider: google_storage
  container: prunes
  key_environ: GCS_KEY