seed: 2069
# model
model:
  resnet_cifar:
    num_classes: 10
    num_layers: 20
# data
train_data:
  cifar10:
    train: true
    shuffle: true
    drop_last: true
val_data:
  cifar10:
    train: false
    shuffle: false
    drop_last: false
# training
train_batch_size: 1024
val_batch_size: 2000
optimizer:
  sgd:
    lr: 1.2
    momentum: 0.9
    weight_decay: 0.0001
schedulers:
  multistep_warmup:
    t_warmup: 5ep
    milestones:
    - 80ep
    - 120ep
    gamma: 0.1
max_duration: 160ep
algorithms:
  channels_last: {}
callbacks:
  lr_monitor: {}
dataloader:
  persistent_workers: false
loggers:
  file:
    filename: log.txt
    log_level: 3
  wandb:
    project: lth_diet
    entity: prunes
object_store:
  provider: google_storage
  container: prunes
  key_environ: GCS_KEY