seed: 1234
# model
model:
  resnet_cifar:
    num_classes: 10
    num_layers: 20
# data
pretrain_data:
  cifar10:
    train: true
train_data:
  cifar10:
    train: true
val_data:
  cifar10:
    train: false
# training:
pretrain_batch_size: 1024
train_batch_size: 1024
val_batch_size: 1000
pretrain_optimizer:
  sgd:
    lr: 1.6
    momentum: 0.9
    weight_decay: 0.0001
optimizer:
  sgd:
    lr: 1.6
    momentum: 0.9
    weight_decay: 0.0001
pretrain_schedulers:
  multistep_warmup:
    t_warmup: 384ba
    milestones:
    - 3840ba
    - 5760ba
    gamma: 0.1
schedulers:
  multistep:
    milestones:
    - 3840ba
    - 5760ba
    gamma: 0.1
pretrain_duration: 384ba
max_duration: 7680ba
algorithms:
  channels_last: {}
callbacks:
  lr_monitor: {}
# boilerplate
loggers:
  file:
    log_level: 3
  wandb:
    project: lth_diet
    entity: prunes
dataloader:
  persistent_workers: false
object_store:
  provider: google_storage
  container: prunes
  key_environ: GCS_KEY