seed: 1234
# model
model:
  resnet_cifar:
    num_classes: 10
    num_layers: 56
load_exp:
  seed: 6174
  model:
    resnet_cifar:
      num_classes: 10
      num_layers: 56
  train_data:
    cinic10:
      train: true
  val_data:
    cinic10:
      train: false
  train_batch_size: 256
  val_batch_size: 1000
  optimizer:
    sgd:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001
  schedulers:
    multistep:
      milestones:
      - 15625ba
      - 23440ba
      gamma: 0.1
  max_duration: 31250ba
  algorithms:
    channels_last: {}
  callbacks:
    lr_monitor: {}
  rewinding_steps: 0ba
  pretrain_data:
    cinic10:
      train: true
  pretrain_optimizer:
    sgd:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0001
load_replicate: 0
train_data:
  cinic10:
    train: true
val_data:
  cinic10:
    train: false
train_batch_size: 256
val_batch_size: 1000
optimizer:
  sgd:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
schedulers:
  multistep:
    milestones:
    - 15625ba
    - 23440ba
    gamma: 0.1
max_duration: 31250ba
algorithms:
  channels_last: {}
callbacks:
  lr_monitor: {}
loggers:
  file:
    log_level: 3
  wandb:
    project: lth_diet
    entity: prunes
    tags: lottery_test
dataloader:
  persistent_workers: false
object_store:
  provider: google_storage
  container: prunes
  key_environ: GCS_KEY