# experiment
replicate: 0
seed: 2069
# model and data
model:
  resnet_cifar:
    num_layers: 20
    num_classes: 10
train_data:
  cifar10:
    train: true
    shuffle: true
    drop_last: true
val_data:
  cifar10:
    train: false
    shuffle: false
    drop_last: false
# training
max_duration: 160ep
train_batch_size: 128
val_batch_size: 1000
optimizer:
  sgd:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
schedulers:
  - multistep:
      milestones:
        - 31200ba
        - 46800ba
      gamma: 0.1
algorithms:
  - channels_last: {}
callbacks:
  - lr_monitor: {}
  - run_directory_uploader:
      provider: google_storage
      container: prunes
      key_environ: GCS_KEY
loggers:
  - tqdm: {}
device: 
  gpu: {}
precision: amp
save_interval: null
dataloader:
  num_workers: 8
  prefetch_factor: 2
  persistent_workers: false
  pin_memory: true
  timeout: 0