seed: 2069
# model
model:
  resnet_cifar:
    num_classes: 10
    num_layers: 20
# data
train_data:
  cifar10:
    train: true
    shuffle: true
    drop_last: true
val_data:
  cifar10:
    train: false
    shuffle: false
    drop_last: false
# training
train_batch_size: 128
val_batch_size: 1000
optimizer:
  sgd:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
schedulers:
- multistep:
    milestones:
    - 31200ba
    - 46800ba
    gamma: 0.1
max_duration: 160ep
object_store:
  provider: google_storage
  container: prunes
  key_environ: GCS_KEY